name: Update Target Data

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 21 * * THU'  # Runs every Thursday at 21:00 UTC

permissions:
  contents: write  # Explicitly grant write access

jobs:
  update_target_data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PERSONAL_GITHUB_TOKEN }}  # Use the personal token

    steps:    
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up R 
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install R Dependencies
        run: |
          install.packages(c("dplyr", "lubridate", "readxl", "tidyr"))
        shell: Rscript {0}
        
      - name: Generate target CSV files
        run: Rscript scripts/get_target_data.R  
        
      - name: Add new files
        run: git add target-data/ 
          
      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -am 'update target data' || echo "No changes to commit"
      
      - name: Push changes with personal token
        env:
          GITHUB_PAT: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          git push https://${{ secrets.PERSONAL_GITHUB_TOKEN }}@github.com/ai4castinghub/hospitalization-forecast.git HEAD:main || echo "No changes to commit"
